captain_console/captain_console/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index, name="homepage-index"),
    path('admin/', include('admin.urls')),
    path('products/', include('product.urls')),
    path('user/', include('user.urls')),
    path('cart/', include('cart.urls')),
    path('manufacturers/', include('manufacturer.urls')),
    path('about/', include('about_us.urls')),
    path('order/', include('order.urls')),
]

# GAMLA

#urlpatterns = [
    #path('', views.index, name="homepage-index"),
    #path('admin/', admin.site.urls),
    #path('manufacturers/', include('manufacturer.urls')),
    #path('products/', include('product.urls')),
    #path('sales/', include('sale.urls')),
    #path('about/', include('about_us.urls')),
    #path('accessory/', include('accessory.urls')),
    #path('user/', include('user.urls')),
    #path('cart/', include('cart.urls'))
#]

captain_console/cart/urls.py
import cart
from . import views
from django.urls import path

urlpatterns = [
    path('', cart.views.view, name="cart-index"),
    path('addToCart', cart.views.add_to_cart, name="cart-add"),
    path('numberOfItems', cart.views.number_of_items, name="cart-count"),
    path('deleteFromCart', cart.views.del_from_cart, name="cart-del")
]

captain_console/product/models.py
from django.db import models
from django.forms import ModelForm, widgets

# Create your models here.
from django.shortcuts import render, get_object_or_404

from manufacturer.models import Manufacturer
from django.contrib.auth.models import User


class Console(models.Model):
    name = models.CharField(max_length=255)

    # description = models.CharField(max_length=999, blank=True)
    # price = models.FloatField()
    # manufacturer = models.ForeignKey(Manufacturer, on_delete=models.CASCADE)
    def __str__(self):
        return self.name


class GameGenre(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Type(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=255)
    description = models.CharField(max_length=999)
    price = models.DecimalField(max_digits=100, decimal_places=2, default=0)
    manufacturer = models.ForeignKey(Manufacturer, on_delete=models.CASCADE)
    type = models.ForeignKey(Type, on_delete=models.CASCADE)
    developer = models.CharField(max_length=255)
    release_year = models.FloatField()
    console = models.ForeignKey(Console, on_delete=models.CASCADE)
    genre = models.ForeignKey(GameGenre, on_delete=models.CASCADE)
    on_sale = models.BooleanField()

    def __str__(self):
        return self.name


class ProductImage(models.Model):
    image = models.CharField(max_length=999)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

    def __str__(self):
        return self.image


class SearchHistory(models.Model):
    name = models.CharField(max_length=999)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default="")

captain_console/templates/game/game_details.html
{% extends "base.html" %}
{% block content %}
    <h1>{{ games.name }}</h1>
    <p>{{ games.description }}</p>

    <p>Developer: {{ games.developer }}</p>
    {% for product_image in games.productimage_set.all %}
        <img src="{{ product_image.image }}" class="product-img"/>
    {% endfor %}
    <div style="text-align: right ">

        <h4>Price: ${{ games.price }}</h4>
        {% if games.on_sale == True %}
            <p>20% off now</p>
        {% endif %}
        <button type="button" class="btn bg-cart" onclick="addToCart({{ games.id }});"><i
                class="fa fa-cart-plus mr-2"></i> Add to cart
        </button>
        <p></p>
        <button type="button" class="btn bg-cart" onclick="addToWishlist({{ games.id }});">
            <i class="glyphicon glyphicon-heart">
            </i> Add to wishlist
        </button>
        <p></p>
        <a type="button" href="{% url 'review_index' games.id %}" class="btn bg-cart"> Add
        review</a>
    </div>
    <h1>Reviews</h1>
    {% for review in reviews %}
        {% if review.product_id == games.id %}
            {% for user in users %}
                {% if user.id == review.user_id %}
                    <h6>{{ user.username }}</h6>
                {% endif %}
            {% endfor %}
            <div class="well">
                <p>{{ review.review }}</p>
            </div>

        {% endif %}
    {% endfor %}
{% endblock %}

captain_console/templates/game/index.html
{% extends 'base.html' %}
{% block content %}
    <h1 class="red">Games</h1>

    <div class="bar">

        <div class="sorter">
            <h4>Sort products by: </h4>
            <div class="dropdown">
              <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Choose ...
              </button>

                <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
                <button type="submit" id="sorter_button" class="dropdown-item" onclick="sorter_function('name', '/games')">
                    Name
                </button>
                <button type="submit" id="sorter_button" class="dropdown-item" onclick="sorter_function('price', '/games')">
                    Price
                </button>
                <button type="submit" id="sorter_button" class="dropdown-item" onclick="sorter_function('release_year', '/games')">
                    Release year
                </button>
                </div>
            </div>
        </div>

        <div class="filter">
            <h4>Filter products by manufacturer: </h4>
            <div class="dropdown">
              <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Choose ...
              </button>

                <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
                    {% for manu in manufacturers %}
                        {% if manu.name != 'NA' %}
                            <button class="dropdown-item" type="button" onclick="filter_function({{ manu.id }}, '/games')">{{ manu }}</button>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>

    <div class="products">
        {% for product in products %}
            {% include 'game/single_game.html' with product=product %}
        {% endfor %}
    </div>
{% endblock %}

captain_console/templates/game/single_game.html
<div class="well product">
    {% if product.type_id == 1 %}
        <div class="card">
            <div class="card-body">
                <a href="games/{{ product.id }}">
                    <img src={{ product.productimage_set.first.image }} class="product-img">

                </a>
                <h6 class="font-weight-semibold mb-2"><a href="games/{{ product.id }}"
                                                         class="text-default mb-2"
                                                         data-abc="true">
                    {{ product.name }}

                </a></h6>
                <div>
                    {% if product.on_sale == True %}
                        <p>20% off now</p>
                    {% else %}
                        <br>
                    {% endif %}
                </div>

                <div>
                    <h3 class="mb-0 font-weight-semibold">${{ product.price }}</h3>
                    <button type="button" class="btn bg-cart" onclick="addToCart({{ product.id }});"><i class="fa fa-cart-plus mr-2"></i> Add to cart
                    </button>
                </div>

            </div>
        </div>
    {% endif %}
</div>